version: '3.8'

services:
  api:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    environment:
      
      - DATABASE_HOST=postgres        
      - DATABASE_PORT=5432                    
      - DATABASE_USER=postgres             
      - DATABASE_PASSWORD=postgres   
      - DATABASE_NAME=postgres        

      
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      
      - JWT_SECRET=your_secret_key

    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: redis_queue
    ports:
      - "6379:6379"